# Generated by Django 5.0.3 on 2024-06-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completed_trainings', '0005_alter_completedexercise_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completed_training',
            old_name='name',
            new_name='training_name',
        ),
    ]
