# Generated by Django 5.0.3 on 2024-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_trainings', '0006_rename_name_completed_training_training_name'),
        ('exercises', '0007_delete_trainingplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='completedexercise',
            name='exercise',
            field=models.ManyToManyField(to='exercises.exercises'),
        ),
    ]
