# Generated by Django 5.0.3 on 2024-06-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_trainings', '0007_remove_completedexercise_exercise_and_more'),
        ('exercises', '0007_delete_trainingplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='completedexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercises'),
        ),
    ]
