# Generated by Django 5.0.3 on 2024-06-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completed_trainings', '0008_remove_completedexercise_exercise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTraining',
        ),
    ]
