# Generated by Django 5.0.3 on 2024-06-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_userwieght'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWieght',
            new_name='UserWeight',
        ),
    ]
