# Generated by Django 5.0.3 on 2024-04-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userid_exerciseid',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='userid_exerciseid',
            old_name='user_id',
            new_name='user',
        ),
    ]
