# Generated by Django 5.0.3 on 2024-04-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercises_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
