# Generated by Django 5.0.3 on 2024-04-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_trainingplans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingPlans',
        ),
    ]
